### ISSUE TITLE
Auto-sync feature

### ISSUE THREAD

**Issue by David-Guillot** [Codoc-os/django-opensearch-dsl#1]
Hi there,

Thanks for initiating this fork, may it become as popular as the original `django-elasticsearch-dsl` :+1: 

I see auto-sync feature has been deleted, and I think that would prevent some people to use this lib, as it was [one of the main features](https://django-elasticsearch-dsl.readthedocs.io/en/latest/about.html#features) of the original lib. Maybe its implementation was not perfect (naming, separation of concerns), but it was working pretty well, and one could easily disable it for a given `Document` by setting `ignore_signals` to `True` ([somewhere here in the original libs docs](https://django-elasticsearch-dsl.readthedocs.io/en/latest/quickstart.html#declare-data-to-index)).

I would be happy to open a PR re-introducing this feature if you're okay with it.

**Comment by qcoumes** [comment]
I have nothing against reintroducing the feature.

If you could add an `OPENSEARCH_DSL_IGNORE_SIGNALS` to be able to disable the signals globally, that would be perfect.
`Document.Django.ignore_signals` should be able to override this setting as needed, kinda like how `OPENSEARCH_DSL_AUTO_REFRESH` works.

**Comment by David-Guillot** [comment]
Actually the original lib was exposing a setting named `ELASTICSEARCH_DSL_AUTOSYNC` (defaulting to `True`) that was allowing to enable/disable auto-sync globally (see [docs](https://django-elasticsearch-dsl.readthedocs.io/en/latest/settings.html#elasticsearch-dsl-autosync)). So I'll just take the original code and apply it, and we'll discuss about naming.
