### ISSUE TITLE
When will OpenSearch 1.1 and 1.2 be supported?

### ISSUE THREAD

**Issue by barseghyanartur** [Codoc-os/django-opensearch-dsl#15]
When will OpenSearch 1.1 and 1.2 be supported?

**Comment by qcoumes** [comment]
As far as I know, there is no issue with the package when running OpenSearch 1.1 or 1.2, this you encounter any problem ?

**Comment by qcoumes** [comment]
It seems to even work perfectly fine with Opensearch 2.0.1

**Comment by barseghyanartur** [comment]
Why are requirements hard-pinned to [~=1.0.0](https://github.com/Codoc-os/django-opensearch-dsl/blob/master/setup.py#L33)? Can they be made more loose?

**Comment by qcoumes** [comment]
For information, Django 4.1 is supposed to release the 3th of August, I will release a new version of `django-opensearch-dsl` containing the new requirements, as well as the latest feature implemented, right afterward.
