### ISSUE TITLE
prepare method not working in ObjectField

### ISSUE THREAD

**Issue by Ameer-Amr** [Codoc-os/django-opensearch-dsl#20]
I have an ObjectField like this,

    priceRange = fields.ObjectField(
        attr='get_price_range',
        properties={
            'currency': fields.ObjectField(
                properties={
                    'code': fields.TextField(),
                },
            ),
            'min': fields.IntegerField(),
            'max': fields.IntegerField()
        },
    )

and wrote a prepare method that I want to return the required response from the same model's another method. like this,

    def prepare_priceRange(self, instance):
        return instance.get_price_range_for_search

but when I reindex the document it failed and didn't return anything.

**Comment by David-Guillot** [comment]
Hi @Ameer-Amr ,

Have you tried removing the `attr` attribute from your field declaration?
- It's used to define which source model instance property to call, so it might conflict with your `prepare` method
- In my codebase I have `ObjectFields` with `prepare` methods and without this `attr` attribute, and it works

**Comment by qcoumes** [comment]
Hi @Ameer-Amr, the `prepare_` methods prevails `attr`, as you can see in the following snippet:

            prep_func = getattr(self, "prepare_%s_with_related" % name, None)
            if prep_func:
                fn = partial(prep_func, related_to_ignore=self._related_instance_to_ignore)
            else:
                prep_func = getattr(self, "prepare_%s" % name, None)
                if prep_func:
                    fn = prep_func
                else:
                    # attr is used here
                    fn = partial(field.get_value_from_instance, field_value_to_ignore=self._related_instance_to_ignore)

So you don't need to defined the `attr` argument : just called your `DemoModel.get_price_range`  method from the `prepare_priceRange()`.

On the other hand, I don't think the fact your indexation fail is related to the use of the `attr` argument. The value from `prepare_priceRange()` should have been used.

Is `instance.get_price_range_for_search` a property ? If not you should call it, `prepare_` methods should return a value, not a callable.

**Comment by Ameer-Amr** [comment]
Thanks @qcoumes, it is now working.
