### ISSUE TITLE
TypeError: update() missing 1 required positional argument: 'action'

### ISSUE THREAD

**Issue by Ameer-Amr** [Codoc-os/django-opensearch-dsl#21]
Hi Team,
I tried to implement the latest version in my local with update-related model instances.
and I overwrite the update function with my requirement, like this 👇🏻

    def update(self, thing, action, *args, refresh=None, **kwargs):
        if isinstance(thing, MyModel) and action == "index":
            if not thing.is_active or not thing.is_visible:
                return super(ModelDocument, self).update(
                    thing, action="delete", *args, refresh=refresh, **kwargs)
        return super(ModelDocument, self).update(
            thing, action, *args, refresh=refresh, **kwargs)

and when I tried to index the document I got the above-mentioned error saying "TypeError: update() missing 1 required positional argument: 'action' ".  so I fixed the issue in my local. so here I want to mention that, I think we missed the positional argument in the registries.py file (update_related and delete_related). so, can I make a PR of the same?

**Comment by qcoumes** [comment]
Sure go ahead.

We might be mocking too much (or too early) in the thests.

**Comment by Colin-Seifer** [comment]
Mocking was exactly the issue here. I'd like to dive in a bit more and update the tests, but for now I added a hotfix for the issue so it's not breaking anything https://github.com/Codoc-os/django-opensearch-dsl/pull/24

**Comment by qcoumes** [comment]
Released with `0.4.1`, thanks @Colin-Seifer
