### ISSUE TITLE
related_models attribute raises object has no attribute 'get_instances_from_related'

### ISSUE THREAD

**Issue by jlariza** [Codoc-os/django-opensearch-dsl#45]
Good day,

I'm trying to use the `related_models` field in my documents to update the index when the related models is updated. However, If I add a model to that field, It always raises `object has no attribute 'get_instances_from_related'`

I'm not sure what I'm missing. The documentation mentions nothing and the example shows no extra configuration so it is impossible to know what's happening.

Thank you,

**Comment by qcoumes** [comment]
You're right, the documentation about this method is missing.

You can use [`django-elasticsearch-document`'s explanation](https://django-elasticsearch-dsl.readthedocs.io/en/latest/fields.html?highlight=get_instances_from_related#handle-relationship-with-nestedfield-objectfield) in the meantime, it works exactly the same way.

To summarise, `get_instances_from_related` should be a method of your `Document` class which expects an instance of one of the models declared in `Django.related_models` and returns the associated instance(s) of your `Django.model`.
Another way to explain it is that it is used to know what instance(s) of `Django.model` should be reindexed when an instance of one of the related models is updated.

**Comment by qcoumes** [comment]
Documentation added in #53
