### ISSUE TITLE
CelerySignalProcessor causes DoesNotExist error when used with django_celery_results

### ISSUE THREAD

**Issue by JordanHyatt** [Codoc-os/django-opensearch-dsl#58]
line 87 of handle_save_task: 

`instance = apps.get_model(app_label, model).objects.get(pk=pk)`

**Comment by jlariza** [comment]
I'm getting the same error but when running migrations; [this line](https://github.com/Codoc-os/django-opensearch-dsl/blob/master/django_opensearch_dsl/signals.py#L87) raises

`LookupError: No installed app with label 'migrations'`

**Comment by iwalucas** [comment]
Any plans on merging the PR?

**Comment by qcoumes** [comment]
We're waiting for some changes on the PR, you can follow it here: #59

**Comment by qcoumes** [comment]
Fixed in #63 and released in [v0.6.1](https://github.com/Codoc-os/django-opensearch-dsl/releases/tag/v0.6.1).
