### ISSUE TITLE
Unable to delete index

### ISSUE THREAD

**Issue by adlindenberg** [Codoc-os/django-opensearch-dsl#68]
Hi there. 

Am I missing something? I'm running `./manage.py opensearch index delete` and accept all indices that it lists to delete

Then I'm immediately hit with `The provided expression [index_name] matches an alias, specify the corresponding concrete indices instead`. Why? What can I do about this? Seems I'm completely unable to delete an index with the management command?

**Comment by qcoumes** [comment]
Hello, did you change any of the indices' names (defined in `<DocumentClass>.Index.name`) after creating them?

It seems one of the names is an alias and not the name used when creating the associated index.

Can you run the following in a `python3 manage.py shell` and share the output of the prints :

```python
from opensearchpy.connection.connections import connections
print(connections.get_connection().cat.indices())
print(connections.get_connection().cat.aliases())
```

as well as the output of `python3 manage.py opensearch list`
